const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function addHoldingsWindow(html,products){
 const data=JSON.stringify(products).replace(/</g,'\\u003c');
 const style=`<style>.holdings-open{padding:10px 16px;border:1px solid #2563eb;border-radius:8px;background:#edf4ff;color:#1d4ed8;cursor:pointer;font:inherit}.holdings-dialog{width:min(900px,calc(100vw - 48px));max-height:85vh;padding:20px;border:0;border-radius:14px;color:#20314a}.holdings-dialog::backdrop{background:#14223899}.holdings-header{display:flex;align-items:center;justify-content:space-between;gap:16px}.holdings-header h2{margin:0;font-size:20px}.holdings-tools{display:flex;flex-wrap:wrap;gap:12px;margin:16px 0}.holdings-tools input,.holdings-tools select{font:inherit;padding:8px;max-width:100%;box-sizing:border-box}.holdings-table{overflow:auto;max-height:55vh}.holdings-table table{width:100%}.holdings-table thead{position:sticky;top:0;background:#edf4ff}.holdings-table td:last-child{text-align:right}.holdings-close{font:inherit;cursor:pointer;padding:8px 12px}.holdings-dialog tbody td:nth-child(2){white-space:normal;min-width:140px}body:has(.holdings-dialog[open]){overflow:hidden}</style>`;
 const dialog=`<dialog class="holdings-dialog" aria-labelledby="holdings-title"><div class="holdings-header"><h2 id="holdings-title"></h2><button type="button" class="holdings-close">닫기</button></div><p id="holdings-date"></p><div class="holdings-tools"><label>종목 검색 <input id="holdings-search" type="search" placeholder="종목명 또는 티커" /></label><label>정렬 <select id="holdings-sort"><option value="weight-desc">비중 높은 순</option><option value="weight-asc">비중 낮은 순</option><option value="name">종목명 순</option></select></label></div><p id="holdings-count" aria-live="polite"></p><div class="holdings-table"><table><thead><tr><th scope="col">순위</th><th scope="col">종목명</th><th scope="col">티커 / 종목코드</th><th scope="col">편입 비중</th></tr></thead><tbody id="holdings-body"></tbody></table></div></dialog>`;
 const script=`<script>(()=>{const products=${data},dialog=document.querySelector('.holdings-dialog'),search=document.getElementById('holdings-search'),sort=document.getElementById('holdings-sort'),body=document.getElementById('holdings-body');let product;const render=()=>{const query=search.value.trim().toLocaleLowerCase(),ranked=[...product.rows].sort((a,b)=>b.weight-a.weight).map((r,i)=>({...r,rank:i+1})),rows=ranked.filter(r=>(r.name+' '+r.code).toLocaleLowerCase().includes(query));rows.sort(sort.value==='name'?(a,b)=>a.name.localeCompare(b.name,'ko'):sort.value==='weight-asc'?(a,b)=>a.weight-b.weight:(a,b)=>b.weight-a.weight);body.replaceChildren();for(const row of rows){const tr=document.createElement('tr');for(const value of [row.rank,row.name,row.code,Number(row.weight).toFixed(2)+'%']){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.textContent='검색 결과가 없습니다.';tr.append(td);body.append(tr);}document.getElementById('holdings-count').textContent='전체 '+product.rows.length+'종목 · 표시 '+rows.length+'종목';};const open=code=>{product=products[code];if(!product)return;search.value='';sort.value='weight-desc';document.getElementById('holdings-title').textContent=product.name+' 전체 구성 종목';document.getElementById('holdings-date').textContent='자료 기준일 '+product.date;render();dialog.showModal();search.focus();};document.querySelectorAll('.holdings-open').forEach(b=>b.addEventListener('click',()=>open(b.dataset.etf)));document.querySelectorAll('nav a[href^="#etf-"]').forEach(a=>a.addEventListener('click',e=>{if(products[a.hash.slice(5)]){e.preventDefault();open(a.hash.slice(5));}}));search.addEventListener('input',render);sort.addEventListener('change',render);document.querySelector('.holdings-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});})();</script>`;
 for(const code of Object.keys(products))html=html.replace(`<section id="etf-${esc(code)}">`, `<section id="etf-${esc(code)}"><button type="button" class="holdings-open" data-etf="${esc(code)}">전체 구성 종목 보기 (${products[code].rows.length}종목)</button>`);
 return html.replace('</main>',dialog+'</main>').replace('</html>',style+script+'</html>');
}
