const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function parseSox(data){
 const result=data?.chart?.result?.[0];
 if(data?.chart?.error||!result)throw Error('SOX chart data unavailable');
 const values=result.indicators?.quote?.[0]?.close;
 const points=(result.timestamp||[]).map((t,i)=>({t,v:values?.[i]})).filter(p=>Number.isFinite(p.v));
 if(points.length<2)throw Error('SOX chart points unavailable');
 return {meta:result.meta,points};
}
export async function fetchSox(fetcher=fetch){
 const get=async(range,interval)=>{const r=await fetcher(`https://query1.finance.yahoo.com/v8/finance/chart/%5ESOX?range=${range}&interval=${interval}`,{headers:{'user-agent':'Mozilla/5.0'},signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('SOX data HTTP '+r.status);return parseSox(await r.json());};
 const [day,week,history]=await Promise.all([get('1d','5m'),get('5d','30m'),get('5y','1d')]);
 const price=day.meta.regularMarketPrice,previous=day.meta.previousClose;
 if(!Number.isFinite(price)||!Number.isFinite(previous)||previous<=0||!Number.isFinite(day.meta.regularMarketTime))throw Error('SOX latest quote unavailable');
 const last=day.points.at(-1);if(last.t<day.meta.regularMarketTime)day.points.push({t:day.meta.regularMarketTime,v:price});
 return {price,previous,time:day.meta.regularMarketTime,day:day.points,week:week.points,history:history.points,fetchedAt:new Date().toISOString()};
}
export function soxCard(data){
 const change=data.price-data.previous,pct=change/data.previous*100,color=change>=0?'#f4a8b0':'#8ab4f8';
 const f=n=>n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
 const stamp=new Intl.DateTimeFormat('ko-KR',{timeZone:'America/New_York',year:'numeric',month:'long',day:'numeric',hour:'numeric',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(data.time*1000));
 const payload=JSON.stringify(data).replace(/</g,'\\u003c');
 return `<section id="sox-card" class="sox-card" aria-labelledby="sox-title"><style>
 .sox-card{background:#111318;color:#e8eaed;border:1px solid #30333c;border-radius:16px;padding:24px;margin:24px 0}.sox-card h2{margin:4px 0 12px;font-size:22px;color:#e8eaed}.sox-card .sox-kicker{font-size:12px;letter-spacing:.06em;color:#9aa0a6}.sox-card .sox-quote{display:flex;gap:14px;align-items:baseline;flex-wrap:wrap}.sox-card .sox-price{font-size:32px;font-weight:700;letter-spacing:-.04em}.sox-card .sox-change{font-size:24px;color:${color}}.sox-card .sox-time,.sox-card .sox-source{color:#9aa0a6;font-size:12px}.sox-card svg{width:100%;min-width:0!important;display:block}.sox-card svg text{fill:#9aa0a6;font-size:12px}.sox-card .sox-periods{display:flex;gap:8px;flex-wrap:wrap;border-top:1px solid #282b33;padding-top:16px}.sox-card button{background:transparent;color:#bdc1c6;border:0;border-radius:8px;padding:9px 18px;cursor:pointer;font:inherit}.sox-card button[aria-pressed="true"]{background:#292c35;color:#fff}.sox-card a{color:#b9cbf9}.sox-card .sox-source{margin-bottom:0}.sox-card .sox-description{font-size:13px;color:#bdc1c6;margin:8px 0}.sox-card .sox-reading{min-height:22px;font-size:13px;color:#bdc1c6}@media(max-width:600px){.sox-card{padding:18px}.sox-card .sox-price{font-size:28px}.sox-card button{padding:8px 12px}.sox-card .sox-change{font-size:20px}.sox-card svg text{font-size:22px}}
 </style><div class="sox-kicker">NASDAQ · SOX</div><h2 id="sox-title">필라델피아 반도체 지수</h2><div class="sox-quote"><span class="sox-price">${f(data.price)}</span><span class="sox-change">${change>=0?'↑ +':'↓ '}${pct.toFixed(2)}%</span><span style="color:${color}">(${change>=0?'+':''}${f(change)}) <small>전일 대비</small></span></div><p class="sox-time">${esc(stamp)} · 미국 동부시간</p><p class="sox-description">미국 반도체 업종의 흐름을 보여주는 SOX 지수</p><svg id="sox-chart" viewBox="0 0 1000 300" role="img" aria-label="필라델피아 반도체 지수 1일 차트"></svg><p class="sox-reading" aria-live="polite"></p><div class="sox-periods" role="group" aria-label="차트 기간">${['1D','5D','1M','6M','YTD','1Y','5Y'].map((v,i)=>`<button type="button" data-period="${v}" aria-pressed="${i===0}">${v}</button>`).join('')}</div><p class="sox-source">자료: <a href="https://finance.yahoo.com/quote/%5ESOX/" target="_blank" rel="noopener">Yahoo Finance</a> · <a href="https://www.google.com/finance/quote/SOX:INDEXNASDAQ" target="_blank" rel="noopener">Google Finance에서 보기</a> · 게시 시 갱신 · 지연 시세</p></section>
 <script>(()=>{const d=${payload},card=document.getElementById('sox-card'),svg=card.querySelector('svg'),reading=card.querySelector('.sox-reading'),buttons=[...card.querySelectorAll('[data-period]')],fmt=n=>n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});let active='1D',points=[],x,y;
 const date=(t,short)=>new Intl.DateTimeFormat('ko-KR',{timeZone:'America/New_York',...(short?active==='1D'?{hour:'numeric',minute:'2-digit'}:{month:'numeric',day:'numeric'}:{year:'numeric',month:'numeric',day:'numeric',hour:'numeric',minute:'2-digit'})}).format(new Date(t*1000));
 function render(period){active=period;const end=d.history.at(-1).t,start=new Date(end*1000);if(period==='1M')start.setUTCMonth(start.getUTCMonth()-1);if(period==='6M')start.setUTCMonth(start.getUTCMonth()-6);if(period==='1Y')start.setUTCFullYear(start.getUTCFullYear()-1);if(period==='YTD'){start.setUTCMonth(0,1);start.setUTCHours(0,0,0,0);}points=period==='1D'?d.day:period==='5D'?d.week:period==='5Y'?d.history:d.history.filter(p=>p.t>=start.getTime()/1000);buttons.forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.period===period)));svg.setAttribute('aria-label','필라델피아 반도체 지수 '+period+' 차트');const base=period==='1D'?d.previous:points[0].v,lo=Math.min(base,...points.map(p=>p.v)),hi=Math.max(base,...points.map(p=>p.v)),pad=Math.max((hi-lo)*.15,1),min=lo-pad,max=hi+pad;x=t=>72+(t-points[0].t)/Math.max(1,points.at(-1).t-points[0].t)*900;y=v=>245-(v-min)/(max-min)*220;const c=points.at(-1).v>=base?'#f4a8b0':'#8ab4f8',path=points.map((p,i)=>(i?'L':'M')+x(p.t).toFixed(2)+' '+y(p.v).toFixed(2)).join(' ');svg.innerHTML='<defs><linearGradient id="sox-fill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="'+c+'" stop-opacity=".25"/><stop offset="1" stop-color="'+c+'" stop-opacity="0"/></linearGradient></defs>'+Array.from({length:5},(_,i)=>{const v=min+(max-min)*i/4;return '<line x1="72" x2="972" y1="'+y(v)+'" y2="'+y(v)+'" stroke="#272a32"/><text x="62" y="'+(y(v)+4)+'" text-anchor="end">'+Math.round(v).toLocaleString('en-US')+'</text>';}).join('')+'<path d="'+path+' L972 245 L72 245 Z" fill="url(#sox-fill)"/><line x1="72" x2="972" y1="'+y(base)+'" y2="'+y(base)+'" stroke="#737883" stroke-dasharray="2 6"/><text x="972" y="'+(y(base)-8)+'" text-anchor="end">'+(period==='1D'?'전일 종가 ':'기간 시작 ')+fmt(base)+'</text><path d="'+path+'" fill="none" stroke="'+c+'" stroke-width="3"/><circle cx="972" cy="'+y(points.at(-1).v)+'" r="5" fill="'+c+'"/>'+[0,.5,1].map(r=>{const t=points[0].t+(points.at(-1).t-points[0].t)*r;return '<text x="'+x(t)+'" y="278" text-anchor="'+(r===0?'start':r===1?'end':'middle')+'">'+date(t,true)+'</text>';}).join('')+'<line id="sox-cursor" y1="25" y2="245" stroke="#9aa0a6" stroke-dasharray="4 4" visibility="hidden"/>';reading.textContent=date(points[0].t,false)+' ~ '+date(points.at(-1).t,false)+' · 미국 동부시간';}
 buttons.forEach(b=>b.addEventListener('click',()=>render(b.dataset.period)));svg.addEventListener('pointermove',e=>{const box=svg.getBoundingClientRect(),px=(e.clientX-box.left)/box.width*1000;let p=points.reduce((a,b)=>Math.abs(x(a.t)-px)<Math.abs(x(b.t)-px)?a:b);const line=svg.querySelector('#sox-cursor');line.setAttribute('x1',x(p.t));line.setAttribute('x2',x(p.t));line.setAttribute('visibility','visible');reading.textContent=date(p.t,false)+' · '+fmt(p.v);});svg.addEventListener('pointerleave',()=>{svg.querySelector('#sox-cursor').setAttribute('visibility','hidden');});render('1D');})();</script>`;
}
export function insertSox(html,data){const marker='<section class="overall-holdings"';if(!html.includes(marker))throw Error('Overall holdings section missing');return html.replace(marker,soxCard(data)+marker);}
